### ISSUE TITLE
Html report, multiple spaces in filename showed as 1 space character.

### ISSUE THREAD

**Issue by limelime** [limelime/FilesHub#7]

**Comment by limelime** [comment]
Add the following CSS in template.html
```CSS
body div {white-space: pre;}
```
